version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/randori_library

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements_dev.txt
      - run:
          name: radon
          command: sh run_radon.sh
      - run:
          name: run tests
          command: sh run_tests.sh

workflows:
  version: 2
  test:
    jobs:
      - build_and_test
